# This rule is not used by the project lightsout itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over lightsout.techsupport.mk.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lightsout
    app.kubernetes.io/managed-by: kustomize
  name: lightsoutschedule-admin-role
rules:
- apiGroups:
  - lightsout.techsupport.mk
  resources:
  - lightsoutschedules
  verbs:
  - '*'
- apiGroups:
  - lightsout.techsupport.mk
  resources:
  - lightsoutschedules/status
  verbs:
  - get
