{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightsout.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lightsout.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "lightsout.selectorLabels" . | nindent 4 }}
{{- end }}
